# 笔记：定义镜像设定
version: '2'
services:
  configserver:
    image: johncarnell/tmx-confsvr:section12
    ports:
       - "8888:8888"
    # 笔记：端口号映射到主机上
    environment:
      ENCRYPT_KEY:       "IMSYMMETRIC"
  database:
    # 笔记：代码中需要访问的数据库
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      # 笔记：镜像所需要的环境变量
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_DB:       "eagle_eye_local"
  licensingservice:
    # 笔记：开发的微服务——进行配置
    image: johncarnell/tmx-licensing-service:section12
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"
